version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=logipack
    networks:
      - logipack-backend-net
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      dockerfile: Dockerfile
    image: logipack-backend:latest
    container_name: logipack-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/logipack
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=test1234
    networks:
      - logipack-backend-net
    depends_on:
      - postgres
      - datagen

volumes:
  postgres-data:

networks:
  logipack-backend-net:
    driver: bridge