version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: logipack-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=test1234
    volumes:
      - data-postgres:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    container_name: logipack-mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - data-mongodb:/data/db

  rabbitmq:
    container_name: logipack-rabbitmq
    image: rabbitmq:3.8-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 20s
      timeout: 30s
      retries: 3


  datagen:
    image: logipack-datagen:latest
    container_name: logipack-datagen
    environment:
      - HOSTNAMERABBIT=localhost
    depends_on:
      rabbitmq:
        condition: service_healthy


  backend:
    build: .
    image: logipack-backend:latest
    container_name: logipack-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=test1234
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_started
      mongodb:
        condition: service_started
      datagen:
        condition: service_started



volumes:
  data-postgres:
  data-mongodb: