openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'LogiPack Sample API'
  description: Logistics Managment System for a dsitributition company, allowing fleet and package managment and tracking by clients

servers:
  - url: logipack

paths:
  
  /encomendas:
    get:
      summary: Read all Encomendas
      responses:
        '200':
          description: List of all Encomendas 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayofAllEncomendas'
  
  /encomendas/{encomendaID}:
    parameters:
      - name: encomendaID
        description: The unique identifier of a Encomenda
        in: path
        required: true
        schema:
            type : integer
            format: int32
    get:
      summary: Read Encomenda by unique identifier
      responses:
        '200':
          description: Read Encomenda
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Encomenda'

  /estados/encomendas/{encomendaID}:
    put:
      summary: Update State of an Encomenda
      parameters:
        - name: encomendaID
          description: The unique identifier of a Encomenda
          in: path
          required: true
          schema:
              type : integer
              format: int32
      requestBody:
        $ref: '#/components/schemas/EncomendaEstado'
      responses:
        '200':
          description: OK

  /cliente/confirmar/{encomendaID}:
    put:
      summary: Confirm arrival of Encomenda by Client
      parameters:
        - name: encomendaID
          description: The unique identifier of a Encomenda
          in: path
          required: true
          schema:
              type : integer
              format: int32
      responses:
        '200':
          description: OK

  
  /cliente/encomendas/{encomendaID}:
    get:
      summary:  all Encomendas corresponding to a specific Client
      parameters:
        - name: encomendaID
          description: The unique identifier of a Encomenda
          in: path
          required: true
          schema:
              type : integer
              format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayofAllEncomendas'

  /transportadores:
    get:
      summary: Read all Transportadores
      responses:
        '200':
          description: List of all Transportadores 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayofAllTransportadores'


      

  /spacecrafts/{spacecraftId}:
    parameters:
      - name: spacecraftId
        description: The unique identifier of the spacecraft
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/SpacecraftId'
    get:
      summary: Read a spacecraft
      responses:
        '200':
          description: The spacecraft corresponding to the provided `spacecraftId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Spacecraft'
        404:
          description: No spacecraft found for the provided `spacecraftId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:

    Encomenda:
      type: object
      properties:
        id:
          type: integer
        EncomendaEstado:
          type: string
          enum:    
            - REGISTADA
            - EM_TRANSITO
            - ENTREGUE
            - EM_DISTRIBUICAO
        emissor:
          type: string
        destinatario:
          type: string
        Localizacao:
          type: object
          description: Localizacao object
        peso:
          type: number
        transportador:
          type: integer
          description: Transportador identifier
        timestamp:
          type: string
        confirmacao:
          type: boolean
        cliente:
          type: integer
          description: Cliente identifier
    
    Localizacao:
      type: object
      properties:
        id:
          type: integer
        distrito:
          type: string
        concelho:
          type: string
        freguesia:
          type: string
        rua:
          type: string
        codigopostal:
          type: string

    EncomendaMongo:
      type: object
      description: History of Encomenda States
      properties:
        _id:
          type: string
        encomenda:
          type: integer
          description: encomenda identifier
        history:
          type: array
          items:
            type: object
          description: array of EncomendaEstadoMongo objects

    EncomendaEstadoMongo:
      type: object
      properties:
        estado: 
          type: string
        timestamp:
          type: string
        confirmacao:
          type: boolean

    Transportador:
      type: object
      properties:
        id: 
          type: integer
        nome:
          type: string
        email:
          type: string
        telefone:
          type: string
        matricula:
          type: string
        timestamp:
          type: string
        TransportadorEstado:
          type: string
          enum:    
            - INATIVO
            - EM_TRANSITO
            - PARADO
            - EM_PAUSA
        encomendas:
          description: array of encomenda Objects 
          type: array
          items: 
            type: object

    TransportadorMongo:
      description: History of Transportador States
      type: object
      properties:
        _id: 
          type: string
        transportador:
          type: integer
          description: Transportador identifier
        history:
          type: array
          items:
            type: object
          description: array of TransportadorEstadoMongo objects

    TransportadorEstadoMongo:
      type: object
      properties: 
        estado:
          type: string
        timestamp:
          type: string
    
    ArrayofAllEncomendas:
      type: array
      items: 
        type: object
        $ref: '#/components/schemas/Encomenda'
    
    ArrayofAllTransportadores:
      type: array
      items: 
        type: object
        $ref: '#/components/schemas/Transportador'

