openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'LogiPack Sample API'
  description: Logistics Managment System for a dsitributition company, allowing fleet and package managment and tracking by clients

servers:
  - url: logipack

paths:

  /login/cliente:
    post:
      summary: Validates client Login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Credentials'

        '401':
          description: Wrong credentials 
          content:
            application/json:
              schema: {}

    
  /login/transportador:
    post:
      summary: Validates Transportador Login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Credentials'

        '401':
          description: Wrong credentials 
          content:
            application/json:
              schema: {}
    

  /login/administrador:
    post:
      summary: Validates Administrador Login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Credentials'

        '401':
          description: Wrong credentials 
          content:
            application/json:
              schema: {}
    

  /encomendas?status=estado:
    get:
      parameters:
        - in: query
          name: estado
          required: false
          schema:
              type : string
          description: Encomendas only with that type

      summary: Read all Encomendas
      responses:
        '200':
          description: List of all Encomendas 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayofAllEncomendas'
  
  /encomendas/{encomendaID}:
    parameters:
      - name: encomendaID
        description: The unique identifier of a Encomenda
        in: path
        required: true
        schema:
            type : integer
            format: int32
    get:
      summary: Read Encomenda by unique identifier
      responses:
        '200':
          description: Read Encomenda
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Encomenda'


  /encomendas/{encomendaID}/details:
    get:
      parameters:
      - name: encomendaID
        description: The unique identifier of a Encomenda
        in: path
        required: true
        schema:
            type : integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EncomendaMongo'



  /estados/encomendas/{encomendaID}:
    put:
      summary: Update State of an Encomenda
      parameters:
        - name: encomendaID
          description: The unique identifier of a Encomenda
          in: path
          required: true
          schema:
              type : integer
              format: int32
      requestBody:
        $ref: '#/components/schemas/EncomendaEstado'
      responses:
        '200':
          description: OK

  /cliente/confirmar/{encomendaID}:
    put:
      summary: Confirm arrival of Encomenda by Client
      parameters:
        - name: encomendaID
          description: The unique identifier of a Encomenda
          in: path
          required: true
          schema:
              type : integer
              format: int32
      responses:
        '200':
          description: OK

  
  /cliente/{id}/encomendas:
    get:
      summary:  all Encomendas corresponding to a specific Client
      parameters:
        - name: id
          description: The unique identifier of a Client
          in: path
          required: true
          schema:
              type : integer
              format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayofAllEncomendas'

  /cliente/{id}/notificacoes:
    get:
      summary: Notifications of specific Client
      parameters:
        - name: id
          description: The unique identifier of a Client
          in: path
          required: true
          schema:
              type : integer
              format: int32
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayofNotification'


    delete:
      summary: Delete all Notifications of specific Client
      parameters:
        - name: id
          description: The unique identifier of a Client
          in: path
          required: true
          schema:
              type : integer
              format: int32
      responses:
        '200':
          description: Ok
  


  /transportadores:
    get:
      summary: Read all Transportadores
      responses:
        '200':
          description: List of all Transportadores 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayofAllTransportadores'


  /transportadores/{TrasnportadorId}:
    get:
      parameters:
        - name: TrasnportadorId
          description: The unique identifier of a Transportador
          in: path
          required: true
          schema:
              type : integer
              format: int32
      summary: Read Transportador by unique identifier
      responses:
        '200':
          description: Read Transportador
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transportador'

  /estados/transportadores/{TrasnportadorId}:
    put:
      summary: Update State of a Transportador
      parameters:
        - name: TrasnportadorId
          description: The unique identifier of a Trasnportador
          in: path
          required: true
          schema:
              type : integer
              format: int32
      requestBody:
        $ref: '#/components/schemas/TransportadorEstado'
      responses:
        '200':
          description: OK
  
  /transportadores/{TrasnportadorId}/details:
    get:
      summary: Return history of transportador's states
      parameters:
        - name: TrasnportadorId
          description: The unique identifier of a Trasnportador
          in: path
          required: true
          schema:
              type : integer
              format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransportadorMongo'

  /encomendas/historico/ano:
    get:
      summary: History of Packages in a year by month
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: {}
                

  /encomendas/historico/mes:
    get:
      summary: History of Packages in a month by weak
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: {}


  /encomendas/historico/semana:
    get:
      summary: History of Packages in a weak by day
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: {}

components:
  schemas:
    Login:
      type: object
      properties:
        email: 
          type: string
        password: 
          type: string

    
    Credentials:
      type: object
      properties:
        token: 
          type: string
        id: 
          type: string

    Notification:
      type: object
      properties:
        encomendaId:
          type: string
        newState:
          type: string
        timestamp:
          type: string

    Encomenda:
      type: object
      properties:
        id:
          type: integer
        EncomendaEstado:
          type: string
          enum:    
            - REGISTADA
            - EM_TRANSITO
            - ENTREGUE
            - EM_DISTRIBUICAO
        emissor:
          type: string
        destinatario:
          type: string
        Localizacao:
          type: object
          description: Localizacao object
        peso:
          type: number
        transportador:
          type: integer
          description: Transportador identifier
        timestamp:
          type: string
        confirmacao:
          type: boolean
        cliente:
          type: integer
          description: Cliente identifier
    
    Localizacao:
      type: object
      properties:
        id:
          type: integer
        distrito:
          type: string
        concelho:
          type: string
        freguesia:
          type: string
        rua:
          type: string
        codigopostal:
          type: string

    EncomendaMongo:
      type: object
      description: History of Encomenda States
      properties:
        _id:
          type: string
        encomenda:
          type: integer
          description: encomenda identifier
        history:
          type: array
          items:
            type: object
          description: array of EncomendaEstadoMongo objects

    EncomendaEstadoMongo:
      type: object
      properties:
        estado: 
          type: string
        timestamp:
          type: string
        confirmacao:
          type: boolean

    Transportador:
      type: object
      properties:
        id: 
          type: integer
        nome:
          type: string
        email:
          type: string
        telefone:
          type: string
        matricula:
          type: string
        timestamp:
          type: string
        TransportadorEstado:
          type: string
          enum:    
            - INATIVO
            - EM_TRANSITO
            - PARADO
            - EM_PAUSA
        encomendas:
          description: array of encomenda Objects 
          type: array
          items: 
            type: object

    TransportadorMongo:
      description: History of Transportador States
      type: object
      properties:
        _id: 
          type: string
        transportador:
          type: integer
          description: Transportador identifier
        history:
          type: array
          items:
            type: object
          description: array of TransportadorEstadoMongo objects

    TransportadorEstadoMongo:
      type: object
      properties: 
        estado:
          type: string
        timestamp:
          type: string
    
    ArrayofAllEncomendas:
      type: array
      items: 
        type: object
        $ref: '#/components/schemas/Encomenda'

    
    ArrayofNotifications:
      type: array
      items: 
        type: object
        $ref: '#/components/schemas/Notification'
    
    ArrayofAllTransportadores:
      type: array
      items: 
        type: object
        $ref: '#/components/schemas/Transportador'

          
