version: "3"

services:
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    ports:
        # AMQP protocol port
        - '5672:5672'
        # HTTP management UI
        - '15672:15672'
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 10
    networks:
      - logipack-datagen-net

  datagen:
    build:
      dockerfile: Dockerfile
    image: logipack-datagen:latest
    container_name: logipack-datagen
    environment:
      - HOSTNAMERABBIT=localhost
    depends_on:
      - rabbitmq
    networks:
      - logipack-datagen-net

networks:
  logipack-datagen-net:
    driver: bridge