version: "3"

services:
  rabbitmq:
    container_name: logipack-rabbitmq
    image: rabbitmq:3.8-management-alpine
    restart: always
    ports:
        - 5672:5672
        - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 20s
      timeout: 30s
      retries: 7
    networks:
      - logipack-datagen-net

  datagen:
    build: .
    image: logipack-datagen:latest
    container_name: logipack-datagen
    environment:
      - HOSTNAMERABBITMQ=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - logipack-datagen-net

networks:
  logipack-datagen-net:
    driver: bridge