spring:
  profiles:
    active: usage_message
  
  datasource: 
    platform: postgres
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "test1234"
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: false
    database: POSTGRESQL
    hibernate:
      # ddl-auto: update
      ddl-auto: create-drop

  data:
      mongodb:
        host: localhost
        port: 27017
        database: logipack

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


# Rabbitmq env variables
rabbitmq:
  queues:
    encomendas: queue_encomendas
    transportadores: queue_transportadores
    clientes: queue_clientes

  exchange: logipack_exchange

  routing:
    keys:
      encomendas: routing_key_encomendas
      transportadores: routing_key_transportadores
      clientes: routing_key_clientes


logging:
  level:
    org: ERROR

tutorial:
  client:
    duration: 10000