spring:
  profiles:
    active: usage_message
  
  datasource: 
    platform: postgres
    url: "jdbc:postgresql://127.0.0.1:5432/logipack"
    username: "postgres"
    password: "test1234"
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
      # ddl-auto: create-drop

logging:
  level:
    org: ERROR

tutorial:
  client:
    duration: 10000