spring:
  profiles:
    active: usage_message
  
  datasource: 
    platform: postgres
    url: "jdbc:postgresql://127.0.0.1:5432/logipack"
    username: "postgres"
    password: "test1234"
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: false
    database: POSTGRESQL
    hibernate:
      # ddl-auto: update
      ddl-auto: create-drop

  data:
      mongodb:
        user: admin
        password: admin
        uri: mongodb://host:9000/logipack



# Rabbitmq env variables
rabbitmq:
  queues:
    encomendas: queue_encomendas
    transportadores: queue_transportadores

  exchange: logipack_exchange

  routing:
    keys:
      encomendas: routing_key_encomendas
      transportadores: routing_key_transportadores

logging:
  level:
    org: ERROR

tutorial:
  client:
    duration: 10000