name: Deployment in Virtual Machine
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Send mail
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.office365.com
        server_port: 587
        username: ${{ secrets.EMAIL_ADDRESS }} # GitHub Actions secret
        password: ${{ secrets.EMAIL_PASSWORD }} # GitHub Actions secret
        subject: deploy
        body: deploy
        to: logipack-cd@outlook.pt
        from: Logi Pack
